### ISSUE TITLE
大佬好

### ISSUE THREAD

**Issue by fennuxiaomeng** [usaginya/usaginya#1]
大佬好233 
我是之前在steam评论区下载了您制作的一款叫
“狼头RPG v2.2x防卡补丁_v2”的人
就是解决wolf RPG切出去卡死的那个程序 一直都很好用 十分感谢您
不过最近似乎wolf版本更新了。。一些作者制作的游戏这个程序无法成功打上补丁了
想问您有更新的计划么 不管怎么样还是谢谢您了~

**Comment by usaginya** [comment]
> 大佬好233 我是之前在steam评论区下载了您制作的一款叫 “狼头RPG v2.2x防卡补丁_v2”的人 就是解决wolf RPG切出去卡死的那个程序 一直都很好用 十分感谢您 不过最近似乎wolf版本更新了。。一些作者制作的游戏这个程序无法成功打上补丁了 想问您有更新的计划么 不管怎么样还是谢谢您了~

如果能提供一下游戏程序、可以尝试更新一下。
一般来说狼头rpg的游戏程序是可以替换使用的、只有一些版本变化比较大的游戏才可能出现一些运行问题

**Comment by fennuxiaomeng** [comment]
就是一些最近出的小黄油 都出现了该情况
比如：
sukebei.nyaa.si/view/3464379
这款 用的引擎我看是wolf 2.271（2021.7）
使用您之前制作的补丁提示是补丁失败
确实没尝试过用以前的wolf主程序替换。。主要是我也没留233玩完就删了都
您有空可以看看
十分感谢

**Comment by usaginya** [comment]
> 就是一些最近出的小黄油 都出现了该情况 比如： sukebei.nyaa.si/view/3464379 这款 用的引擎我看是wolf 2.271（2021.7） 使用您之前制作的补丁提示是补丁失败 确实没尝试过用以前的wolf主程序替换。。主要是我也没留233玩完就删了都 您有空可以看看 十分感谢

更新了补丁、支持了wolf rpg v2.27以上的游戏程序
看了v2.27的指令、貌似有对窗口状态检查的参数部分进行一点修改、但不知道为什么这个bug还是没修复、大部分指令也是和旧版本差不多
v2.27的游戏数据看起来不能直接被旧版本程序兼容、所以还是只能用新版游戏程序
补丁地址和密码与之前一样 **/s/1X0zZQUxzBuQtPQ2D9yZKTA           解压：9**

**Comment by fennuxiaomeng** [comment]
> > 就是一些最近出的小黄油 都出现了该情况 比如： sukebei.nyaa.si/view/3464379 这款 用的引擎我看是wolf 2.271（2021.7） 使用您之前制作的补丁提示是补丁失败 确实没尝试过用以前的wolf主程序替换。。主要是我也没留233玩完就删了都 您有空可以看看 十分感谢
> 
> 更新了补丁、支持了wolf rpg v2.27以上的游戏程序 看了v2.27的指令、貌似有对窗口状态检查的参数部分进行一点修改、但不知道为什么这个bug还是没修复、大部分指令也是和旧版本差不多 v2.27的游戏数据看起来不能直接被旧版本程序兼容、所以还是只能用新版游戏程序 补丁地址和密码与之前一样 https://pan.baidu.com/s/1X0zZQUxzBuQtPQ2D9yZKTA** https://pan.baidu.com/s/1X0zZQUxzBuQtPQ2D9yZKTA 解压：9**

好的 十分感谢大佬！
